import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { gsap } from "gsap/dist/gsap"
import { useGSAP } from "@gsap/react"
import "./globals.css"

const inter = Inter({
  subsets: ["latin"],
})

gsap.registerPlugin(useGSAP)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  )
}
